---
output:
  pdf_document: default
  html_document: default
---
# Literature

**This version: `r Sys.Date()`**

## List of papers - Classic

- **@Akerlof1970**: Must read about asymmetry of information.
- **@Fama1997**
- **@FamaFrench1983a**
- **@FamaFrench1983b**
- **@LaPorta1998**: Must read about Law and Finance.
- **@Jensen1976**: The origins of Agency conflicts and Corporate Governance.
- **@Jensen1986**
- **@Markowitz1952**: The origins of portfolio.


## List of papers - Corporate Finance
- **@Almeida2011**: Nice application of DiD in Finance.
- **@Strebulaev2013**: Why some firms go zero-leveraged?

## List of papers - Governance
- **@Bertrand2003**: The paper that suggests that managers like a "quite life".
- **@Black2017**: About construct validity of "Governance"
- **@Boyd2017**: A must read paper about methodological issues in CG research.
- **@ChenDongLin2020**: A nice paper about institutional investment and CSR performance: they have a sound RDD application.
- **@Dickinson2011**: A way to identify a firm's stage of life using cash flows.
- **@SchiehllMartins2016**: About the different associations of Governance and Investor Protection.



## List of papers - Open Science
- **RAC's editorials**: I recommend all RAC's Editorials since 2018 about Open Science, Open data and related topics (https://rac.anpad.org.br/index.php/rac)
- **@Babin2020**: Replication methods in academic research.
- **@Beugelsdijk2020**: The JIBS editorial about Open Science
- **@Harvey2017**: discusses the publication of "significant" results. Read to understand what is the publication bias.
- **@Harvey2019**: A discussion about replications.
- **@Spiegel2019**: About replication and open data.
- **@MendesCristiana2021**: What is Salami Science?
- **@VanRaaij2018**: About Data Reuse


## List of materials - Econometrics
- **@Abadie2010**: An example of Synthetic Control.
- **@AngristPischke2008**: Good to learn about causality methods.
- **@AngristPischke2014**: Easier to read than previous one. I use this one in classes.
- **@Bascle2008**: Also easy to read review about endogeneity and methods.
- **@Bertrand2004**
- **@Brooks2019**: Book with nice examples and lots of codes.
- **@Bowen2017**: Important to see the development of causal methods.
- **@CappelleriTrochim2015**: Introduction to RDD.
- **@Gow2016**: Good review about causal methods.
- **@Gormley2014**: This is here so I remember to read (didn't read yet).
- **@Jiang2017**: A discussion about instrumental variables.
- **@KahnWhited2018**: Identification is not causality, and vice-versa.
- **@Lindner2019**: Some ideas aboout multicollinearity.
- **@McLean2012**: Good article to learn how to make interpretations of coefficients and marginal effects. They are very didactic.
- **@Murray2006**: Nice examples of instruments
- **@Petersen2009**: Discussion about standard-errors in Finance.
- **@Reeb2012**: Easy to reed review about endogeneity in International Business.
- **@Roodman2009**: Important to estimate GMM in stata.
- **@Roodman2009xtabond2**: Important to estimate GMM in Stata.
- **@Schiozer2020**: A tutorial about Diff-in-Diff, with open data and open code.
- **@Stuart2010**    
- **@Wasserstein2016**: About p-value and the importance of not using a single metric to assess the quality of a model.
- **@Wooldridge2019**: The basic must-to-read book about econometrics.




## List of books - Finance
- **@BrighamEhrhardt2012**: ótimo livro para graduação e MBAs, mas não gosto da forma da tradução.
- **@BerkDemarzo2013**: Meu livro preferido para graduação e MBAs. No entanto, a versão boa é a inglês.
- **@BodieKaneMarcus2013**: 


## List of papers - Science
- **@aguinis2011editorial**: Good reflection about Editor's roles.

