---
output:
  word_document: default
  html_document: default
  pdf_document: default
---

# Master Syllabus (2020.2) 

**Date: 2020/02**



**PONTIFICAL CATHOLIC UNIVERSITY OF RIO DE JANEIRO**

**IAG – BUSINESS SCHOOL**

**Course:** INTERMEDIATE CORPORATE FINANCE AND GOVERNANCE

**ADM 2675** – Tópicos Especiais em Finanças - 2GA

**Professor:**	Henrique C. Martins	(hcm@iag.puc-rio.br)

**Period:** 2020.2

**Tuesdays 13h-16h**


## Syllabus 

Empirical methods for causal inference research in corporate finance and governance: randomized trials, regression, and instrumental variables, fixed effects and panel data, differences-in-differences, regression discontinuity design. Topics of corporate capital structure, dividend policy, financial restrictions, and cash flow sensitivities. Topics of agency theory, corporate governance mechanisms, and investor protection.

## Goals

This course prepares the student to research corporate finance and corporate governance topics using methods for causal inference. It is divided into two parts. In the first part, we discuss the empirical methods for causal inference. In the second part, we discuss selected topics of corporate finance, capital structure, and dividend policy; and selected topics of corporate governance. Students will gain an understanding of how to deal empirically with the research in corporate finance and governance.

## Program

-	Methods for causal inference;
-	Corporate finance decisions;
-	Capital structure and Investment decisions;
-	Corporate governance and agency conflict;
-	Selected topics in corporate governance.


 
## Grading

This course emphasizes the theoretical discussion and understanding of all topics. Students will answer quizzes in the first 30 minutes of class. The day of the quizzes will be randomly scheduled. There will be an Exam on the last day. Participation in class with comments, questions, and general discussions is incentivized.

- Participation in class:	**10%**
- Quizzes (random days):	**40%**
- Coding marathon:	**25%**
- Individual exam:	**25%**



## Mandatory readings 

- **@AngristPischke2014**

-	**@AtanasovBlack2016** 

-	**@RobertsWhited2013**

- **Articles selected by the instructor**


## Schedule (days) 

***Part 1 - Empirical research in finance***

- **Day 1)	Potential outcome and causality I (selection bias and randomization)**

  -	**@AngristPischke2014** – chapter 1
  -	**@Bowen2017** 
  -	https://www.youtube.com/watch?v=iPBV3BlV7jk
  -	https://www.youtube.com/watch?v=6YrIDhaUQOE

- **2)	Potential outcome and causality II (regression)**

  -	**@AngristPischke2014** – chapter 2
  -	**@AtanasovBlack2016** – section 1 and 2.1
  
- **3)	Instrumental variables and RDD**

  -	**@AngristPischke2014** – chapter 3
  - **@AngristPischke2014** – chapter 4
  -	**@Bennedsen2007**
  -	**@CappelleriTrochim2015**
  
- **4)	Differences-in-differences and Propensity score matching**

  - **@AngristPischke2014** – chapter 5
  -	**@Schiozer2020**
  -	**@AtanasovBlack2016** – section 2.4
  -	**@Stuart2010**
  -	https://www.youtube.com/watch?v=02DYZkpc3-o 

- **5)	Fixed effects and panel data**

  -	**@RobertsWhited2013** – section 7
  -	**@Lemmon2008**


- **6)	Coding marathon**

  - **Students will create a code estimating methods selected by the instructor**


***Part 2 - Corporate Finance and Corporate Governance***

- **7)	Capital structure and Cash holdings I**

  -	**@RajanZingales1995**
  - **@Almeida2011**
  -	**@Opler1999**


- **8)	Capital structure and Cash holdings II (20 Outubro)**

  -	**@AlmeidaCampello2007**
  -	**@AlmeidaCampelloWeisbach2004**

- **9)	Corporate Governance I (29 Outubro) **

  -	**@ShleiferVishny1997**
  -	**@LaPorta1998**
  -	https://hbr.org/2019/10/a-guide-to-the-big-ideas-and-debates-in-corporate-governance

- **10)	Corporate Governance II  (3 Novembro)**

  -	**@McLean2012**
  -	**@SchiehllMartins2016**

- **11)	Emerging issues: ESG (10 Novembro)**

  -	**@Matos2020**
  -	**@Gibson2020**

- **12)	Board of directors**

  -	**@Adams2010**

- **13)	Schock-based Corporate Finance and Governance**

  -	**@Vig2013**

- **14)	Corporate Finance emerging issues**

  -	**@Zeidan2017** – To be confirmed
  -	**TBA**

- **15)	Corporate Governance emerging issues**
  -	**TBA**

***Part 3 - Final***

- **16)	Exam**

